/*
 * RockPaperScissors.java
 * Author: Rohan Malik
 * Submission Date: September 4, 2016
 * Purpose: The user plays Rock, Paper, Scissors against the computer
 */

import java.util.Scanner;

public class RockPaperScissors{
	
	/**
 	* The majority of the game is done in the main method.
 	* There are loops and switch statements that check what the user 
 	* enters and compare it to a random hand generated by
 	* the program
 	* @param args   This is just System.in
 	*/ 
	public static void main(String[] args) {
	

	Scanner scan = new Scanner(System.in);
	int wins = 0;
	int losses = 0;
	int ties = 0;
	boolean keepgoing  = true;

	System.out.print("\tStart Game Rock_Paper_Scissors\n");
	
	while (keepgoing) {
		int random = (int) ((Math.random() * 3) + 1);
		String com = getHand(random);
		boolean incorrect = true;
		String input = "";
		int user = 0;;
		while (incorrect) {
		System.out.println("Enter your choice(R for rock, P for paper or S for Scissors) OR Enter E to exit:");
		System.out.print("\t");
		input = scan.next();
		incorrect = false;
		//System.out.println("\t" + input);
		switch (input) {
			case "S":
			case "s": user = 3;
			          if (random == 1) {
					lose(com);
					losses++;
				  } else if (random == 2){ 
				  	win(com);
					wins++;
				  } else {
					tie(com);
					ties++;
				  }
				  break;
			case "P":
			case "p": user = 2;
				  if (random == 1) {
					win(com);
					wins++;
				  } else if (random == 2) {
					tie(com);
					ties++;
				  } else {
					lose(com);
					losses++;
				  }
				  break;
			case "R":
			case "r": user = 1;
				  if (random == 1) {
					tie(com);
					ties++;
				  } else if (random == 2) {
					lose(com);
					losses++;
				  } else {
					win(com);
					wins++;
				  }
				  break;
			case "E":
			case "e": keepgoing = false;
				  break;
			default: incorrect = true;
				 System.out.println("Wrong input.");
				 break;
		}
		}
	}		
		System.out.println("\tGame Ended");
		System.out.println("\tNumber of wins = " + wins);
		System.out.println("\tNumber of losses = " + losses);
		System.out.println("\tNumber of ties = " + ties);
		
	
	}
	/**
 	* The getHand takes the random number generated by the
 	* program and converts it to a hand
 	* @param random  must be 1, 2, or 3
 	* @return String  returns a hand
 	*/
	private static String getHand(int random) {
		String hand = "";
		switch (random) {
			case 1:
				hand = "Rock";
				break;
			case 2:
				hand = "Paper";
				break;
			case 3:
				hand = "Scissors";
				break;
		}
		return hand;
	}
	/**
 	* Prints out that the user won
	* @param a  the computer's hand
	*/
	private static void win(String a) {
		System.out.println("\tYou won :) My choice was " + a + ".");		
	}
	/**
 	* Prints out that the user and program tied
 	* @param a  the computer's hand
 	*/ 
	private static void tie(String a) {
		System.out.println("\tTie ==( My choice was " + a + " too");
	}
	/**
 	* Prints out that the user lost
 	* @param a  the computer's hand
 	*/ 
	private static void lose(String a) {
		System.out.println("\tI won :( My choice was " + a + ".");
	}

}
