CC = javac
RM = rm

default: PizzaStore.class Order.class CustomerOrder.class Pizza.class Drink.class Appetizer.class PizzaTest.class

PizzaStore.class: PizzaStore.java
	$(CC) PizzaStore.java

Order.class: Order.java
	$(CC) Order.java

CustomerOrder.class: CustomerOrder.java
	$(CC) CustomerOrder.java

Pizza.class: Pizza.java
	$(CC) Pizza.java

Drink.class: Drink.java
	$(CC) Drink.java

Appetizer.class: Appetizer.java
	$(CC) Appetizer.java

PizzaTest.class: PizzaTest.java
	$(CC) PizzaTest.java

clean:
	$(RM) *.class
